<?php

namespace Thibaud\MeetupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeetupRepository
 *
 * This class was generated by the Dotrine ORM. Add your own custom
 * repository methods below.
 */
class MeetupRepository extends EntityRepository
{
}