parameters:
#    thibaud_rest.example.class: Thibaud\RestBundle\Example

services:
#    thibaud_rest.example:
#        class: %thibaud_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
